### ISSUE TITLE
research function not working for "stuff(py" 

### ISSUE THREAD

**Issue by jakbin** [pysonDB/pysonDB#70]
**Describe the bug**
research function not working for 
```python
>>> print(a.reSearch("name", "stuff(py"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dj/.local/lib/python3.9/site-packages/pysondb/db.py", line 247, in reSearch
    pattern = re.compile(str(_re))
  File "/usr/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 836, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 5
```
**How to reproduce**
```python
from pysondb import db
a=db.getDb("test.json")
a.addMany([{"name": "pysondb", "type": "DB"},{"name": "pysondb-cli", "type": "CLI"},{"name": "fire", "type": "CLI"},{"name": "stuff.py", "type": "GUI"},{"name": "def23@c-py", "type": "TUI"},{"name": "stuff(py", "type": "GUI"}])
print(a.reSearch("name", "stuff(py"))
```
i found this on example/re_search.md .

**Expected behavior**
it should not throw an error.

**Comment by Adwaith-Rajesh** [comment]
This has nothing to do with pysonDB and the error clear states that u've a missing 'closing parenthesis'

**Comment by Adwaith-Rajesh** [comment]
And for you regex you should be using this.

```python
>>> a.reSearch("name", "stuff\(py"))
[{'name': 'stuff(py', 'type': 'GUI', 'id': 115618300909661724}]
```
