### ISSUE TITLE
Problem with installation/distribution 1.6.1. Errors folder does not get installed.

### ISSUE THREAD

**Issue by devleaks** [pysonDB/pysonDB#83]
**Describe the bug**
```
$ pysondb convert a.csv a.json
Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/pysondb", line 5, in <module>
    from pysondb.cli import main
  File "/usr/local/miniconda3/lib/python3.9/site-packages/pysondb/__init__.py", line 1, in <module>
    from .db import getDb
  File "/usr/local/miniconda3/lib/python3.9/site-packages/pysondb/db.py", line 11, in <module>
    from pysondb.errors.db_errors import IdNotFoundError
ModuleNotFoundError: No module named 'pysondb.errors'
```

The pysondb/errors folder does not get installed.

```
$ pip install pyjsondb=1.6.1
pip install pyjsondb==1.6.1
ERROR: Could not find a version that satisfies the requirement pyjsondb==1.6.1 (from versions: 0.0.1)
ERROR: No matching distribution found for pyjsondb==1.6.1
```

I noticed setup.cfg still refers to version = 1.6.0.

**How to reproduce**

**Expected behavior**

**Comment by fredysomy** [comment]
Hey @devleaks 

Will resolve this issue.

Thanks.

**Comment by Adwaith-Rajesh** [comment]
@devleaks the error dir does not contain an `__init__` thus the installer skips it while scanning for packages. you can create a PR if you want.

**Comment by Adwaith-Rajesh** [comment]
https://github.com/pysonDB/pysonDB/pull/84
